
LLMActionSet = {
    'cramped_room' : {
        'onion_dispenser' : ['pick up onion from o0.', 'pick up onion from o1.'],
        'cooking_status': ['turn on c0.'],
        'cooker': ['place onion in c0.'], 
        'plate': ['pick up plate from p0.'],
        'delivery_area': ['place soup for delivery in d0.'],
        'cooked_soup': ['load soup on plate from c0.'],
        'collision_avoidance': ['move away.'],
        'wait': ['wait.'],
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)],
        
    },

    'no_counter_door' : {
        'onion_dispenser' : ['pick up onion from o0.', 'pick up onion from o1.'],
        'cooking_status': ['turn on c0.'],
        'cooker': ['place onion in c0.'], 
        'plate': ['pick up plate from p0.'],
        'delivery_area': ['place soup for delivery in d0.'],
        'cooked_soup': ['load soup on plate from c0.'],
        'collision_avoidance': ['move away.'],
        'wait': ['wait.'],
        'gate': ['open g0.', 'open g1.'],
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)],
    },
    'soup_passing_door' : {
        'onion_dispenser' : ['pick up onion from o0.', 'pick up onion from o1.'],
        
        'cooker': ['place onion in c0.', 'place onion in c1.'], 
        'plate': ['pick up plate from p0.', 'pick up plate from p1.'],
        'delivery_area': ['place soup for delivery in d0.'],
        'cooked_soup': ['load soup on plate from c0.', 'load soup on plate from c1.'],
        'collision_avoidance': ['move away.'],
        'wait': ['wait.'],
        'gate': ['open g0.'],
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)],
    },
    'soup_passing' : {
        'onion_dispenser' : ['pick up onion from o0.', 'pick up onion from o1.'],
        'cooker': ['place onion in c0.', 'place onion in c1.'], 
        'plate': ['pick up plate from p0.', 'pick up plate from p1.'],
        'delivery_area': ['place soup for delivery in d0.'],
        'cooked_soup': ['load soup on plate from c0.', 'load soup on plate from c1.'],
        'collision_avoidance': ['move away.'],
        'wait': ['wait.'],
        'storage_counter_pick_onion': ['pick up onion from s0.', 'pick up onion from s1.', 'pick up onion from s2.', 'pick up onion from s3.'],
        'storage_counter_pick_plate': ['pick up plate from s0.', 'pick up a plate from s1.', 'pick up a plate from s2.', 'pick up a plate from s3.'],
        'storage_counter_pick_soup': ['pick up cooked soup from s0.', 'pick up cooked soup from s1.', 'pick up cooked soup from s2.', 'pick up cooked soup from s3.'],
        'storage_counter_place_onion': ['place onion in s0.', 'place onion in s1.', 'place onion in s2.', 'place onion in s3.'],
        'storage_counter_place_plate': ['place plate in s0.', 'place plate in s1.', 'place plate in s2.', 'place plate in s3'],
        'storage_counter_place_soup': ['place cooked soup in s0.', 'place cooked soup in s1.', 'place cooked soup in s2.', 'place cooked soup in s3'],
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)],
        'kitchen_counter_place_soup': [f'place cooked soup on k{idx}.' for idx in range(50)],
    },
    'coordination_ring' : {
        'onion_dispenser' : ['pick up onion from o0.', 'pick up onion from o1.'],
        'cooking_status': ['turn on c0.', 'turn on c1.'],
        'cooker': ['place onion in c0.', 'place onion in c1.'], 
        'plate': ['pick up plate from p0.'],
        'delivery_area': ['place soup for delivery in d0.'],
        'cooked_soup': ['load soup on plate from c0.', 'load soup on plate from c1.'],
        'collision_avoidance': ['move away.'],
        'counter': ['place onion on k0', 'place plate on k0'],
        'wait': ['wait.'],
        'communication': ['send message: move away.', 'send message: send me a plate in the storage counter.', 'send message: send me an onion in the storage counter.', 'send acknowledgement: okay, i moved away.', 'send acknowledgement: okay, i placed an onion in the storage counter.', 'send acknowledgement: okay, i placed a plate in the storage counter.'],
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)],
        
    },
    'counter_circuit_o_1order' : {
        'onion_dispenser' : ['pick up onion from o0.', 'pick up onion from o1.'],
        'cooking_status': ['turn on c0.', 'turn on c1.'],
        'cooker': ['place onion in c0.', 'place onion in c1.'], 
        'plate': ['pick up plate from p0.'],
        'delivery_area': ['place soup for delivery in d0.'],
        'cooked_soup': ['load soup on plate from c0.', 'load soup on plate from c1.'],
        'collision_avoidance': ['move away.'],
        'counter': ['place onion on k0', 'place plate on k0'],
        'wait': ['wait.'],
        'storage_counter_pick_onion': ['pick up onion from s0.', 'pick up onion from s1.', 'pick up onion from s2.', 'pick up onion from s3.'],
        'storage_counter_pick_plate': ['pick up a plate from s0.', 'pick up a plate from s1.', 'pick up a plate from s2.', 'pick up a plate from s3.'],
        'storage_counter_place_onion': ['place onion in s0.', 'place onion in s1.', 'place onion in s2.', 'place onion in s3.'],
        'storage_counter_place_plate': ['place plate in s0.', 'place plate in s1.', 'place plate in s2.', 'place plate in s3'],
        # 'communication': ['send message: move out of the way.', 'send message: pass me an onion.', 'send message: pass me a plate.']
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)],
    },
    'asymmetric_advantages' : {
        'onion_dispenser' : ['pick up onion from o0.', 'pick up onion from o1.'],
        'cooking_status': ['turn on c0.', 'turn on c1.'],
        'cooker': ['place onion in c0.', 'place onion in c1.'], 
        'plate': ['pick up plate from p0.', 'pick up plate from p1.'],
        'delivery_area': ['place soup for delivery in d0.', 'place soup for delivery in d1.'],
        'cooked_soup': ['load soup on plate from c0.', 'load soup on plate from c1.'],
        'collision_avoidance': ['move away.'],
        'wait': ['wait.'],
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)],
    },
    'forced_coordination' : {
        'onion_dispenser' : ['pick up onion from o0.', 'pick up onion from o1.'],
        'cooking_status': ['turn on c0.', 'turn on c1.'],
        'cooker': ['place onion in c0.', 'place onion in c1.'], 
        'plate': ['pick up plate from p0.', 'pick up plate from p1.'],
        'delivery_area': ['place soup for delivery in d0.', 'place soup for delivery in d1.'],
        'cooked_soup': ['load soup on plate from c0.', 'load soup on plate from c1.'],
        'storage_counter_pick_onion': ['pick up onion from s0.', 'pick up onion from s1.', 'pick up onion from s2.'],
        'storage_counter_pick_plate': ['pick up a plate from s0.', 'pick up a plate from s1.', 'pick up a plate from s2.'],
        'storage_counter_place_onion': ['place onion in s0.', 'place onion in s1.', 'place onion in s2.'],
        'storage_counter_place_plate': ['place plate in s0.', 'place plate in s1.', 'place plate in s2.'],
        'collision_avoidance': ['move away.'],
        'wait': ['wait.'],
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)],
    },
    'bottleneck':
    {
       'onion_dispenser' : ['pick up onion from o0.',],
        'cooking_status': ['turn on c0.', 'turn on c1.'],
        'cooker': ['place onion in c0.', 'place onion in c1.'], 
        'plate': ['pick up plate from p0.'],
        'delivery_area': ['place soup for delivery in d0.'],
        'cooked_soup': ['load soup on plate from c0.', 'load soup on plate from c1.'],
        'collision_avoidance': ['move away.'],
        'counter': ['place onion on k0', 'place plate on k0'],
        'wait': ['wait.'],
        'communication': ['send message: move away.', 'send message: send me a plate in the storage counter.', 'send message: send me an onion in the storage counter.', 'send acknowledgement: okay, i moved away.', 'send acknowledgement: okay, i placed an onion in the storage counter.', 'send acknowledgement: okay, i placed a plate in the storage counter.'],
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)], 
    },

    'centre_pots':
    {
        'onion_dispenser' : ['pick up onion from o0.', 'pick up onion from o1.'],
        'cooking_status': ['turn on c0.', 'turn on c1.'],
        'cooker': ['place onion in c0.', 'place onion in c1.'], 
        'plate': ['pick up plate from p0.', 'pick up plate from p1.'],
        'delivery_area': ['place soup for delivery in d0.', 'place soup for delivery in d1.'],
        'cooked_soup': ['load soup on plate from c0.', 'load soup on plate from c1.'],
        'collision_avoidance': ['move away.'],
        'counter': ['place onion on k0', 'place plate on k0'],
        'wait': ['wait.'],
        'communication': ['send message: move away.', 'send message: send me a plate in the storage counter.', 'send message: send me an onion in the storage counter.', 'send acknowledgement: okay, i moved away.', 'send acknowledgement: okay, i placed an onion in the storage counter.', 'send acknowledgement: okay, i placed a plate in the storage counter.'],
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)], 
    },

    'centre_objects':
    {
       'onion_dispenser' : ['pick up onion from o0.'],
        'cooking_status': ['turn on c0.'],
        'cooker': ['place onion in c0.'], 
        'plate': ['pick up plate from p0.'],
        'delivery_area': ['place soup for delivery in d0.'],
        'cooked_soup': ['load soup on plate from c0.'],
        'collision_avoidance': ['move away.'],
        'counter': ['place onion on k0', 'place plate on k0'],
        'wait': ['wait.'],
        'communication': ['send message: move away.', 'send message: send me a plate in the storage counter.', 'send message: send me an onion in the storage counter.', 'send acknowledgement: okay, i moved away.', 'send acknowledgement: okay, i placed an onion in the storage counter.', 'send acknowledgement: okay, i placed a plate in the storage counter.'],
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)], 
    },

    'large_room':{
        'onion_dispenser' : ['pick up onion from o0.', 'pick up onion from o1.'],
        'cooking_status': ['turn on c0.'],
        'cooker': ['place onion in c0.'], 
        'plate': ['pick up plate from p0.'],
        'delivery_area': ['place soup for delivery in d0.'],
        'cooked_soup': ['load soup on plate from c0.'],
        'collision_avoidance': ['move away.'],
        'counter': ['place onion on k0', 'place plate on k0'],
        'wait': ['wait.'],
        'communication': ['send message: move away.', 'send message: send me a plate in the storage counter.', 'send message: send me an onion in the storage counter.', 'send acknowledgement: okay, i moved away.', 'send acknowledgement: okay, i placed an onion in the storage counter.', 'send acknowledgement: okay, i placed a plate in the storage counter.'],
        'kitchen_counter_pick_onion': [f'pick up onion from k{i}.' for i in range(50)],
        'kitchen_counter_pick_plate': [f'pick up plate from k{i}.' for i in range(50)],
        'kitchen_counter_pick_soup': [f'pick up cooked soup from k{i}.' for i in range(50)],
        'kitchen_counter_place_onion': [f'place onion on k{idx}.' for idx in range(50)], 
        'kitchen_counter_place_plate': [f'place plate on k{idx}.' for idx in range(50)], 
    },
}
